drop table if exists comp.Companies;
drop table if exists jrn.StockJournal;
drop table if exists usr.Defaults;
drop table if exists acc.Accounts;
drop table if exists doc.DocDetails;
drop table if exists doc.Documents
drop table if exists doc.OpJournalStore
drop table if exists doc.Operations
drop table if exists doc.DocumentForms
drop table if exists doc.OperationGroups
drop table if exists doc.Forms
drop table if exists doc.FormsMenu
drop table if exists cat.Agents
drop table if exists cat.ItemTreeItems
drop table if exists cat.ItemTree
drop table if exists cat.Items
drop table if exists cat.Banks
drop table if exists cat.Companies
drop table if exists cat.Warehouses
drop table if exists cat.Vendors
drop table if exists cat.Units

